[package]
name = "rust_from_cpp"
version = "0.1.0"
authors = ["Sergey Murtazin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[lib]
name = "math"
crate-type = ["dylib"]