[package]
name = "cmake_rust_sample"
version = "0.1.0"
authors = ["Sergey Murtazin <sergey.murtazin@kohls.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
